DELIMITER //

CREATE PROCEDURE CreateEmployeeTable()
BEGIN
    CREATE TABLE IF NOT EXISTS `employee` (
        EMP_ID INT AUTO_INCREMENT PRIMARY KEY,
        NAME VARCHAR(50) NOT NULL,
        EMAIL VARCHAR(254) NOT NULL,
        FLOOR_SEAT_SEQ INT
    );
END //

DELIMITER ;